"""
Character metadata for the 9 main Futurama characters.
Display info only — no hand-crafted profiles.
H-MEM structures are built algorithmically from transcript data by pipeline/hmem/build.py.
"""

from typing import Any

CHARACTERS: dict[str, dict[str, Any]] = {
    "fry": {
        "character_id": "fry",
        "display_name": "Philip J. Fry",
        "short_name": "Fry",
        "role": "Delivery boy; 20th-century slacker accidentally frozen and thawed 1000 years later",
        "avatar": "🍕",
        "color": "#E8611A",
        "color_dark": "#8B3A10",
        "tagline": "Not the sharpest human in the box",
    },
    "leela": {
        "character_id": "leela",
        "display_name": "Turanga Leela",
        "short_name": "Leela",
        "role": "Captain of the Planet Express ship; one-eyed mutant raised as an alien",
        "avatar": "👁️",
        "color": "#7B2FBE",
        "color_dark": "#4A1A72",
        "tagline": "The only competent person in the room",
    },
    "bender": {
        "character_id": "bender",
        "display_name": "Bender Bending Rodriguez",
        "short_name": "Bender",
        "role": "Bending unit robot; crew's engineer, cook, and resident sociopath",
        "avatar": "🤖",
        "color": "#8A8A8A",
        "color_dark": "#3A3A3A",
        "tagline": "Bite my shiny metal ass",
    },
    "professor": {
        "character_id": "professor",
        "display_name": "Professor Hubert J. Farnsworth",
        "short_name": "Professor",
        "role": "Ancient senile mad scientist; founder of Planet Express; Fry's distant descendant",
        "avatar": "🧪",
        "color": "#22AA66",
        "color_dark": "#105533",
        "tagline": "Good news, everyone!",
    },
    "zoidberg": {
        "character_id": "zoidberg",
        "display_name": "Dr. John A. Zoidberg",
        "short_name": "Zoidberg",
        "role": "Incompetent alien doctor; Decapodian crustacean desperate for acceptance",
        "avatar": "🦞",
        "color": "#CC3333",
        "color_dark": "#771A1A",
        "tagline": "Why not Zoidberg?",
    },
    "amy": {
        "character_id": "amy",
        "display_name": "Amy Wong",
        "short_name": "Amy",
        "role": "Intern and engineering student; heiress to the Western Hemisphere of Mars",
        "avatar": "💅",
        "color": "#D63384",
        "color_dark": "#7A1948",
        "tagline": "Gleesh!",
    },
    "hermes": {
        "character_id": "hermes",
        "display_name": "Hermes Conrad",
        "short_name": "Hermes",
        "role": "Jamaican bureaucrat; Planet Express accountant; Grade 36 bureaucrat",
        "avatar": "📋",
        "color": "#009944",
        "color_dark": "#005522",
        "tagline": "Sweet three-toed sloth of Ice Planet Barbados!",
    },
    "kif": {
        "character_id": "kif",
        "display_name": "Kif Kroker",
        "short_name": "Kif",
        "role": "Long-suffering lieutenant under Zapp Brannigan; gentle alien in love with Amy",
        "avatar": "💚",
        "color": "#2A8A7A",
        "color_dark": "#154A42",
        "tagline": "*sighs*",
    },
    "zapp": {
        "character_id": "zapp",
        "display_name": "Zapp Brannigan",
        "short_name": "Zapp",
        "role": "Incompetent narcissistic DOOP general; obsessed with his own greatness and Leela",
        "avatar": "⭐",
        "color": "#C8972A",
        "color_dark": "#6B5015",
        "tagline": "I am the man with no name. Zapp Brannigan.",
    },
}
